#!/bin/bash

if [ "$#" -eq 0 ]; then
  echo -e "\nNo parameters have been passed.\n"
  exit 1
fi

if [ ! -r /root/.ssh/id_rsa ]; then
  echo -e "\nWarning: There is no RSA key present in the image at "
  echo -e "the SSH default location '/root/.ssh/id_rsa'.\n"
  echo -e "Add or bind mount one or specify another in the config file.\n"
  echo -e "These are the available RSA keys at /root/.ssh :"
  ls -Al /root/.ssh/
  echo
fi


exec autossh -vNF $@
